name: Kick VOD Downloader

on:
workflow_dispatch:
inputs:
vod_url:
description: 'Kick VOD URL to download'
required: true

jobs:
download_vod:
runs-on: ubuntu-latest

steps:
- name: Download Kick VOD MP4
run: |
echo "Downloading Kick VOD from ${{ github.event.inputs.vod_url }}"
wget -O kick_vod.mp4 "${{ github.event.inputs.vod_url }}"

- name: Upload VOD artifact
uses: actions/upload-artifact@v3
with:
name: kick_vod_mp4
path: kick_vod.mp4
